---

#to work around a bug
pe_install::puppetdb_certname: "%{::clientcert}"


#have to the certnames instead of only dynamically using ::clientcert
#include clientcert at the beginning to make sure local puppetdb is used
#before a central one
puppet_enterprise::puppetdb_host:
 - 'puppet-master-centos'
 - 'compile-master-puppetdb'
puppet_enterprise::puppetdb_port:
 - '8081'
 - '8081'

#this class doesn't take params for puppetdb_host and puppetdb_port which sucks
#we could probably interpolate the server and port from above but this is just
#a prototype
#Since pe_install::puppetdb_certname is a single entry and there's no way to
#override the puppetdb_port in pe_install we get mismatching arrays passed here
puppet_enterprise::profile::controller::puppetdb_urls:
 - 'https://puppet-master-centos:8081'


#Drop puppetdb Java Heap Size
#PE3.2 and above
pe_puppetdb::pe::java_args:
  -Xmx: '256m'
  -Xms: '64m'
#PE3.1 and below
pe_puppetdb::java_args:
  -Xmx: '256m'
  -Xms: '64m'
#Drop the activemq java heap size
pe_mcollective::role::master::activemq_heap_mb: '96'
#Allow access to the puppetdb performance dashboard from non-localhost
#This is insecure and also allows access to all API endpoints without verification
pe_puppetdb::pe::listen_address: '0.0.0.0'

#PE3.7
#Allow access to the puppetdb performance dashboard from non-localhost
#This is insecure and also allows access to all API endpoints without verification
puppet_enterprise::profile::puppetdb::listen_address: '0.0.0.0'
puppet_enterprise::profile::amq::broker::heap_mb: '96'
puppet_enterprise::profile::master::java_args:
  Xmx: '192m'
  Xms: '128m'
  'XX:MaxPermSize': '=96m'
  'XX:PermSize': '=64m'
  'XX:+UseG1GC': ''
puppet_enterprise::profile::puppetdb::java_args:
  Xmx: '128m'
  Xms: '128m'
  'XX:MaxPermSize': '=96m'
  'XX:PermSize': '=64m'
  'XX:+UseG1GC': ''
puppet_enterprise::profile::console::java_args:
  Xmx: '64m'
  Xms: '64m'
  'XX:MaxPermSize': '=96m'
  'XX:PermSize': '=64m'
  'XX:+UseG1GC': ''
puppet_enterprise::master::puppetserver::jruby_max_active_instances: 1  #PE3.7.2 only
puppet_enterprise::profile::console::delayed_job_workers: 1
#shared_buffers takes affect during install but is not managed after
puppet_enterprise::profile::database::shared_buffers: '4MB'
#puppet_enterprise::profile::console::classifier_synchronization_period: 0
#2015.3.2 and above
puppet_enterprise::profile::orchestrator::java_args:
  Xmx: '64m'
  Xms: '64m'
  'XX:+UseG1GC': ''
