---
roles:
  master201621:
    provisioners:
      - type: pe_bootstrap
        role: :master
        #version: '2016.2.1'
        download_root: "http://enterprise.delivery.puppetlabs.net/2016.2/ci-ready"
        version_file: 'http://getpe.delivery.puppetlabs.net/latest/2016.2'

  agent_201621:
    provisioners:
      - type: pe_bootstrap
        #version: '2016.2.0'
        master: 'master201621-centos'
        download_root: "http://enterprise.delivery.puppetlabs.net/2016.2/ci-ready"
        version_file: 'http://getpe.delivery.puppetlabs.net/latest/2016.2'

  master201620:
    provisioners:
      - type: pe_bootstrap
        role: :master
        version: '2016.2.0'
        #download_root: "http://enterprise.delivery.puppetlabs.net/2016.2/ci-ready"
        #version_file: 'http://getpe.delivery.puppetlabs.net/latest/2016.2'

  agent_201620:
    provisioners:
      - type: pe_bootstrap
        version: '2016.2.0'
        master: 'master201620-centos'
        #download_root: "http://enterprise.delivery.puppetlabs.net/2016.2/ci-ready"
        #version_file: 'http://getpe.delivery.puppetlabs.net/latest/2016.2'

#  master201621:
#    provisioners:
#      - type: pe_bootstrap
#        role: :master
#        download_root: "http://enterprise.delivery.puppetlabs.net/2016.1/ci-ready"
#        version_file: 'http://getpe.delivery.puppetlabs.net/latest/2016.1'

#  agent_201621:
#    provisioners:
#      - type: pe_bootstrap
#        version: '2016.2.1'
#        master: 'master201612-centos'
#        download_root: "http://enterprise.delivery.puppetlabs.net/2016.1/ci-ready"
#        version_file: 'http://getpe.delivery.puppetlabs.net/latest/2016.1'
