---
roles:
  master20152:
    provisioners:
      - type: pe_bootstrap
        role: :master
        version: '2015.2.0'
        #download_root: "http://enterprise.delivery.puppetlabs.net/2015.2/ci-ready"
        #version_file: 'http://getpe.delivery.puppetlabs.net/latest/2015.2'

  agent_20152:
    provisioners:
      - type: pe_bootstrap
        version: '2015.2.0'
        master: 'master20152-centos'
        #download_root: "http://enterprise.delivery.puppetlabs.net/2015.2/ci-ready"
        #version_file: 'http://getpe.delivery.puppetlabs.net/latest/2015.2'

  master201521:
    provisioners:
      - type: pe_bootstrap
        role: :master
        version: '2015.2.1'
        #download_root: "http://enterprise.delivery.puppetlabs.net/2015.2/ci-ready"
        #version_file: 'http://getpe.delivery.puppetlabs.net/latest/2015.2'

  agent_201521:
    provisioners:
      - type: pe_bootstrap
        version: '2015.2.1'
        master: 'master201521-centos'
        #download_root: "http://enterprise.delivery.puppetlabs.net/2015.2/ci-ready"
        #version_file: 'http://getpe.delivery.puppetlabs.net/latest/2015.2'

  master201522:
    provisioners:
      - type: pe_bootstrap
        role: :master
        version: '2015.2.2'

  master201523:
    provisioners:
      - type: pe_bootstrap
        role: :master
        version: '2015.2.3'
